name: Test

on:
  pull_request:
  push:
    branches:
      - master

env:
  RUST_BACKTRACE: 1

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: 'Download rust-analyzer nightly'
        run: |
          wget -c -O /tmp/rust-analyzer.gz https://github.com/rust-lang/rust-analyzer/releases/download/nightly/rust-analyzer-x86_64-unknown-linux-gnu.gz
          gunzip /tmp/rust-analyzer.gz
          mv /tmp/rust-analyzer /bin/rust-analyzer
          chmod +x /bin/rust-analyzer
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Test
        run: cargo test
